### ISSUE TITLE
Vagrant: * Unknown configuration section 'hostmanager'.

### ISSUE THREAD

**Issue by celeguim** [0zores/k8s-vagrant#1]
Brother, almost there. 
Running on Mac ...

MacBook-Air:k8s-vagrant celeguim$ vagrant up 
Bringing machine 'k8smaster' up with 'virtualbox' provider...
Bringing machine 'k8snode01' up with 'virtualbox' provider...
Bringing machine 'k8snode02' up with 'virtualbox' provider...
Bringing machine 'k8snode03' up with 'virtualbox' provider...
==> k8smaster: Box 'centos/7' could not be found. Attempting to find and install...
    k8smaster: Box Provider: virtualbox
    k8smaster: Box Version: >= 0
==> k8smaster: Loading metadata for box 'centos/7'
    k8smaster: URL: https://vagrantcloud.com/centos/7
==> k8smaster: Adding box 'centos/7' (v1901.01) for provider: virtualbox
    k8smaster: Downloading: https://vagrantcloud.com/centos/boxes/7/versions/1901.01/providers/virtualbox.box
    k8smaster: Download redirected to host: cloud.centos.org
==> k8smaster: Successfully added box 'centos/7' (v1901.01) for 'virtualbox'!
There are errors in the configuration of this machine. Please fix
the following errors and try again:

Vagrant:
* Unknown configuration section 'hostmanager'.

**Comment by 0zores** [comment]
I forgot to remove the hostmanager piece of code in the Vagrantfile, this code isn't needed anymore, I'll fix and I'll ask to you test again

**Comment by 0zores** [comment]
Fixed, try again

**Comment by 0zores** [comment]
Issue solved
