### ISSUE TITLE
k8s-kubeadm : install required packages

### ISSUE THREAD

**Issue by celeguim** [0zores/k8s-vagrant#2]
Hi brother, we moved one step forward, but still some issue. 

PLAY [all] *********************************************************************

TASK [Gathering Facts] *********************************************************
ok: [k8smaster]

TASK [k8s-kubeadm : update whole os] *******************************************
changed: [k8smaster]

TASK [k8s-kubeadm : add kubernetes repo] ***************************************
changed: [k8smaster]

TASK [k8s-kubeadm : set selinux to permissive] *********************************
changed: [k8smaster]

TASK [k8s-kubeadm : install required packages] *********************************
failed: [k8smaster] (item=[u'epel-release', u'docker', u'kubelet', u'kubeadm', u'kubectl']) => {"changed": false, "item": ["epel-release", "docker", "kubelet", "kubeadm", "kubectl"], "msg": "Unsupported parameters for (yum) module: disable_excludes Supported parameters include: allow_downgrade, bugfix, conf_file, disable_gpg_check, disable_plugin, disablerepo, enable_plugin, enablerepo, exclude, install_repoquery, installroot, list, name, security, skip_broken, state, update_cache, update_only, validate_certs"}
	to retry, use: --limit @/Users/celeguim/k8s-vagrant/ansible/playbook.retry

PLAY RECAP *********************************************************************
k8smaster                  : ok=4    changed=3    unreachable=0    failed=1   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

**Comment by 0zores** [comment]
It seems you are using an Ansible version prior to 2.7, because in this task I'm using the disable_excludes parameter and it was included only in the 2.7 version. I'll fix the README expliciting the recommended versions for Ansible and Vagrant. Try to install the 2.7 version and run again.
Thanks for your help

**Comment by celeguim** [comment]
Indeed, I was using 2.6 and after upgrading it, the issue was gone.
